# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('tweet_lang', models.CharField(default=None, max_length=10)),
                ('user_name', models.CharField(max_length=250)),
                ('user_country', models.CharField(default=None, max_length=50)),
                ('text', models.CharField(default=None, max_length=1000)),
                ('scholaship_name', models.CharField(default=None, max_length=250)),
                ('university', models.CharField(default=None, max_length=250)),
                ('country', models.CharField(default=None, max_length=50)),
                ('deadline', models.DateField(default=None)),
                ('category', models.CharField(default=b'others', max_length=50)),
                ('info_url', models.CharField(default=None, max_length=250)),
                ('longitude', models.DecimalField(decimal_places=8, default=None, max_digits=11)),
                ('latitude', models.DecimalField(decimal_places=8, default=None, max_digits=10)),
                ('marker_type', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tweet_dates_range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
