# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tweet_dates_range',
            new_name='Dates',
        ),
    ]
