# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_auto_20161024_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='relevant',
            field=models.BooleanField(default=True),
        ),
    ]
