# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholarship_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
