# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_auto_20161025_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dates',
        ),
    ]
