# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 22:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_delete_dates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='scholaship_name',
            new_name='scholarship_name',
        ),
    ]
