# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_auto_20161026_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='marker_type',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
