# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0008_auto_20161026_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='marker_name',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
