# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0010_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
    ]
