# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0011_delete_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('tweet_lang', models.CharField(default=None, max_length=10)),
                ('user_name', models.CharField(max_length=250)),
                ('user_country', models.CharField(default=None, max_length=50, null=True)),
                ('text', models.CharField(default=None, max_length=1000)),
                ('scholarship_name', models.CharField(default=None, max_length=250, null=True)),
                ('university', models.CharField(default=None, max_length=250, null=True)),
                ('country', models.CharField(default=None, max_length=50, null=True)),
                ('deadline', models.DateField(default=None, null=True)),
                ('category', models.CharField(default=b'others', max_length=50)),
                ('info_url', models.CharField(default=None, max_length=250, null=True)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10, null=True)),
                ('markerName', models.CharField(default=None, max_length=250, null=True)),
                ('marker_type', models.CharField(default=None, max_length=50, null=True)),
                ('relevant', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='marker_name',
            new_name='markerName',
        ),
        migrations.RenameField(
            model_name='scholarship',
            old_name='marker_type',
            new_name='markerType',
        ),
    ]
