# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0013_auto_20170125_2159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='tweet_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
